[custom.all.cribrum]
type = "local"
path = "."
ipkg = "cribrum.ipkg"

[custom.all.cribrum_test]
type = "local"
path = "test"
ipkg = "test.ipkg"
test = "test.ipkg"

[custom.all.teaweb]
type = "local"
path = "."
ipkg = "teaweb.ipkg"

[custom.all.teaweb_test]
type = "local"
path = "test/teaweb"
ipkg = "teaweb-test.ipkg"
test = "teaweb-test.ipkg"

[custom.all.render-doc]
type = "local"
path = "tools/render-doc"
ipkg = "render-doc.ipkg"

[custom.all.render-docsnav]
type = "local"
path = "tools/render-docsnav"
ipkg = "render-docsnav.ipkg"

[custom.all.run-djotref]
type = "local"
path = "tools/run-djotref"
ipkg = "run-djotref.ipkg"
