||| AUTO-GENERATED by ingest/html-model.ts — do not edit by hand.
||| Source: @webref/elements@2.6.0
||| content-model.ts: sha256 b4fdf07341b18f462e9892be0bfa9e4b21b98cf37734f8a071924003af94ba9e
||| catalog hash: sha256 94fc5df4d8288c9690545bb59d1b60ab1a809514ee547d0906b1b668c3de0a97
module Cribrum.Html.Model.Generated

import Cribrum.Html.Category
import Cribrum.Html.Model.Types

%default total

public export
generatedElements : List ElementSpec
generatedElements =
  [ MkElementSpec "a" False False [Flow, Phrasing, Interactive, Palpable] AnyContent ["download", "href", "hreflang", "ping", "referrerpolicy", "rel", "target", "type"]
  , MkElementSpec "abbr" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "address" False False [Flow, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "area" True False [Flow, Phrasing] NoChildren ["alt", "coords", "download", "href", "ping", "referrerpolicy", "rel", "shape", "target"]
  , MkElementSpec "article" False False [Flow, Sectioning, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "aside" False False [Flow, Sectioning, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "audio" False False [Flow, Phrasing, Embedded, Interactive] AnyContent ["autoplay", "controls", "crossorigin", "loop", "muted", "preload", "src"]
  , MkElementSpec "b" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "base" True False [Metadata] NoChildren ["href", "target"]
  , MkElementSpec "bdi" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "bdo" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) ["dir"]
  , MkElementSpec "blockquote" False False [Flow, Palpable] (OnlyCategories [Flow]) ["cite"]
  , MkElementSpec "body" False False [Flow] (OnlyCategories [Flow]) ["onafterprint", "onbeforeprint", "onbeforeunload", "onhashchange", "onlanguagechange", "onmessage", "onmessageerror", "onoffline", "ononline", "onpagehide", "onpageshow", "onpopstate", "onrejectionhandled", "onstorage", "onunhandledrejection", "onunload"]
  , MkElementSpec "br" True False [Flow, Phrasing] NoChildren []
  , MkElementSpec "button" False False [Flow, Phrasing, Interactive, FormAssociated, Palpable] (OnlyCategories [Phrasing]) ["disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "name", "popovertarget", "popovertargetaction", "type", "value"]
  , MkElementSpec "canvas" False False [Flow, Phrasing, Embedded, Palpable] AnyContent ["height", "width"]
  , MkElementSpec "caption" False False [] (OnlyCategories [Flow]) []
  , MkElementSpec "cite" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "code" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "col" True False [] NoChildren ["span"]
  , MkElementSpec "colgroup" False False [] (OnlyTags ["col", "template"] False) ["span"]
  , MkElementSpec "data" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) ["value"]
  , MkElementSpec "datalist" False False [Flow, Phrasing] AnyContent []
  , MkElementSpec "dd" False False [] (OnlyCategories [Flow]) []
  , MkElementSpec "del" False False [Flow, Phrasing] AnyContent ["cite", "datetime"]
  , MkElementSpec "details" False False [Flow, Interactive, Palpable] AnyContent ["name", "open"]
  , MkElementSpec "dfn" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "dialog" False False [Flow] (OnlyCategories [Flow]) ["open"]
  , MkElementSpec "div" False False [Flow, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "dl" False False [Flow, Palpable] (OnlyTags ["dt", "dd", "div", "script", "template"] False) []
  , MkElementSpec "dt" False False [] (OnlyCategories [Flow]) []
  , MkElementSpec "em" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "embed" True False [Flow, Phrasing, Embedded, Interactive, Palpable] NoChildren ["height", "src", "type", "width"]
  , MkElementSpec "fieldset" False False [Flow, FormAssociated, Palpable] AnyContent ["disabled", "form", "name"]
  , MkElementSpec "figcaption" False False [] (OnlyCategories [Flow]) []
  , MkElementSpec "figure" False False [Flow, Palpable] AnyContent []
  , MkElementSpec "footer" False False [Flow, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "form" False False [Flow, Palpable] (OnlyCategories [Flow]) ["accept-charset", "action", "autocomplete", "enctype", "method", "name", "novalidate", "rel", "target"]
  , MkElementSpec "h1" False False [Flow, Heading, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "h2" False False [Flow, Heading, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "h3" False False [Flow, Heading, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "h4" False False [Flow, Heading, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "h5" False False [Flow, Heading, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "h6" False False [Flow, Heading, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "head" False False [] (OnlyTags ["base", "link", "meta", "noscript", "script", "style", "template", "title"] False) []
  , MkElementSpec "header" False False [Flow, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "hgroup" False False [Flow, Heading, Palpable] (OnlyTags ["h1", "h2", "h3", "h4", "h5", "h6", "p"] False) []
  , MkElementSpec "hr" True False [Flow] NoChildren []
  , MkElementSpec "html" False False [] (OnlyTags ["head", "body"] False) ["xmlns"]
  , MkElementSpec "i" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "iframe" False False [Flow, Phrasing, Embedded, Interactive, Palpable] NoChildren ["allow", "allowfullscreen", "height", "loading", "name", "referrerpolicy", "sandbox", "src", "srcdoc", "width"]
  , MkElementSpec "img" True False [Flow, Phrasing, Embedded, Palpable] NoChildren ["alt", "crossorigin", "decoding", "fetchpriority", "height", "ismap", "loading", "referrerpolicy", "sizes", "src", "srcset", "usemap", "width"]
  , MkElementSpec "input" True False [Flow, Phrasing, Interactive, FormAssociated, Palpable] NoChildren ["accept", "alt", "autocomplete", "checked", "dirname", "disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "height", "list", "max", "maxlength", "min", "minlength", "multiple", "name", "pattern", "placeholder", "readonly", "required", "size", "src", "step", "type", "value", "width"]
  , MkElementSpec "ins" False False [Flow, Phrasing, Palpable] AnyContent ["cite", "datetime"]
  , MkElementSpec "kbd" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "label" False False [Flow, Phrasing, Interactive, Palpable, FormAssociated] (OnlyCategories [Phrasing]) ["for"]
  , MkElementSpec "legend" False False [] (OnlyCategories [Phrasing, Heading]) []
  , MkElementSpec "li" False False [] (OnlyCategories [Flow]) ["value"]
  , MkElementSpec "link" True False [Metadata] NoChildren ["as", "blocking", "color", "crossorigin", "disabled", "fetchpriority", "href", "hreflang", "imagesizes", "imagesrcset", "integrity", "media", "referrerpolicy", "rel", "sizes", "type"]
  , MkElementSpec "main" False False [Flow, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "map" False False [Flow, Phrasing, Palpable] AnyContent ["name"]
  , MkElementSpec "mark" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "math" False False [Flow, Phrasing, Embedded, Palpable] AnyContent []
  , MkElementSpec "menu" False False [Flow, Palpable] (OnlyTags ["li", "script", "template"] False) []
  , MkElementSpec "meta" True False [Metadata] NoChildren ["charset", "content", "http-equiv", "media", "name"]
  , MkElementSpec "meter" False False [Flow, Phrasing, FormAssociated, Palpable] (OnlyCategories [Phrasing]) ["high", "low", "max", "min", "optimum", "value"]
  , MkElementSpec "nav" False False [Flow, Sectioning, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "noscript" False False [Metadata, Flow, Phrasing] AnyContent []
  , MkElementSpec "object" False False [Flow, Phrasing, Embedded, Palpable] AnyContent ["data", "form", "height", "name", "type", "width"]
  , MkElementSpec "ol" False False [Flow, Palpable] (OnlyTags ["li", "script", "template"] False) ["reversed", "start", "type"]
  , MkElementSpec "optgroup" False False [] (OnlyTags ["option", "script", "template"] False) ["disabled", "label"]
  , MkElementSpec "option" False False [] TextOnly ["disabled", "label", "selected", "value"]
  , MkElementSpec "output" False False [Flow, Phrasing, FormAssociated, Palpable] (OnlyCategories [Phrasing]) ["for", "form", "name"]
  , MkElementSpec "p" False False [Flow, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "picture" False False [Flow, Phrasing, Embedded] (OnlyTags ["source", "img", "script", "template"] False) []
  , MkElementSpec "pre" False False [Flow, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "progress" False False [Flow, Phrasing, FormAssociated, Palpable] (OnlyCategories [Phrasing]) ["max", "value"]
  , MkElementSpec "q" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) ["cite"]
  , MkElementSpec "rp" False False [] TextOnly []
  , MkElementSpec "rt" False False [] (OnlyCategories [Phrasing]) []
  , MkElementSpec "ruby" False False [Flow, Phrasing, Palpable] AnyContent []
  , MkElementSpec "s" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "samp" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "script" False True [Metadata, Flow, Phrasing, ScriptSupporting] TextOnly ["async", "blocking", "crossorigin", "defer", "fetchpriority", "integrity", "nomodule", "referrerpolicy", "src", "type"]
  , MkElementSpec "search" False False [Flow, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "section" False False [Flow, Sectioning, Palpable] (OnlyCategories [Flow]) []
  , MkElementSpec "select" False False [Flow, Phrasing, Interactive, FormAssociated, Palpable] (OnlyTags ["option", "optgroup", "hr", "script", "template"] False) ["autocomplete", "disabled", "form", "multiple", "name", "required", "size"]
  , MkElementSpec "slot" False False [Flow, Phrasing] AnyContent ["name"]
  , MkElementSpec "small" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "source" True False [] NoChildren ["height", "media", "sizes", "src", "srcset", "type", "width"]
  , MkElementSpec "span" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "strong" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "style" False True [Metadata] TextOnly ["blocking", "media"]
  , MkElementSpec "sub" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "summary" False False [] (OnlyCategories [Phrasing, Heading]) []
  , MkElementSpec "sup" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "svg" False False [Flow, Phrasing, Embedded, Palpable] AnyContent []
  , MkElementSpec "table" False False [Flow, Palpable] (OnlyTags ["caption", "colgroup", "thead", "tbody", "tfoot", "tr", "script", "template"] False) []
  , MkElementSpec "tbody" False False [] (OnlyTags ["tr", "script", "template"] False) []
  , MkElementSpec "td" False False [] (OnlyCategories [Flow]) ["colspan", "headers", "rowspan"]
  , MkElementSpec "template" False False [Metadata, Flow, Phrasing, ScriptSupporting] AnyContent ["shadowrootclonable", "shadowrootdelegatesfocus", "shadowrootmode"]
  , MkElementSpec "textarea" False True [Flow, Phrasing, Interactive, FormAssociated, Palpable] TextOnly ["autocomplete", "cols", "dirname", "disabled", "form", "maxlength", "minlength", "name", "placeholder", "readonly", "required", "rows", "wrap"]
  , MkElementSpec "tfoot" False False [] (OnlyTags ["tr", "script", "template"] False) []
  , MkElementSpec "th" False False [] (OnlyCategories [Flow]) ["abbr", "colspan", "headers", "rowspan", "scope"]
  , MkElementSpec "thead" False False [] (OnlyTags ["tr", "script", "template"] False) []
  , MkElementSpec "time" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) ["datetime"]
  , MkElementSpec "title" False False [Metadata] TextOnly []
  , MkElementSpec "tr" False False [] (OnlyTags ["td", "th", "script", "template"] False) []
  , MkElementSpec "track" True False [] NoChildren ["default", "kind", "label", "src", "srclang"]
  , MkElementSpec "u" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "ul" False False [Flow, Palpable] (OnlyTags ["li", "script", "template"] False) []
  , MkElementSpec "var" False False [Flow, Phrasing, Palpable] (OnlyCategories [Phrasing]) []
  , MkElementSpec "video" False False [Flow, Phrasing, Embedded, Interactive, Palpable] AnyContent ["autoplay", "controls", "crossorigin", "height", "loop", "muted", "playsinline", "poster", "preload", "src", "width"]
  , MkElementSpec "wbr" True False [Flow, Phrasing] NoChildren []
  ]

public export
generatedGlobalAttrs : List String
generatedGlobalAttrs =
  [ "accesskey"
  , "autocapitalize"
  , "autofocus"
  , "class"
  , "contenteditable"
  , "dir"
  , "draggable"
  , "enterkeyhint"
  , "hidden"
  , "id"
  , "inert"
  , "inputmode"
  , "is"
  , "itemid"
  , "itemprop"
  , "itemref"
  , "itemscope"
  , "itemtype"
  , "lang"
  , "nonce"
  , "popover"
  , "role"
  , "slot"
  , "spellcheck"
  , "style"
  , "tabindex"
  , "title"
  , "translate"
  ]
