// HTML content-model table — hand-curated source of truth for the data
// `@webref/elements@2.6.0` doesn't ship.
//
// `@webref/elements` provides element *names* (and `obsolete` flag).
// Content-model shape (who-nests-in-whom), categories, and per-element
// attribute permissions live only in WHATWG prose, so they're captured
// here in machine-readable form. The ingestion script
// (`ingest/html-model.ts`) cross-validates every row against `@webref`
// (invariant I8) and compiles a deterministic
// `src/Cribrum/Html/Model/Generated.idr` from this table.
//
// Migration path: as `@webref/elements` matures its content-model
// coverage, rows here shrink to override-only.

export type Category =
  | "Metadata"
  | "Flow"
  | "Sectioning"
  | "Heading"
  | "Phrasing"
  | "Embedded"
  | "Interactive"
  | "Palpable"
  | "ScriptSupporting"
  | "FormAssociated";

export type ChildPolicy =
  | { kind: "NoChildren" }
  | { kind: "OnlyTags"; tags: string[]; allowText: boolean }
  | { kind: "OnlyCategories"; cats: Category[] }
  | { kind: "TextOnly" }
  | { kind: "AnyContent" };

export interface ContentModelRow {
  name:         string;
  isVoid:       boolean;
  isRawText:    boolean;
  categories:   Category[];
  childPolicy:  ChildPolicy;
  localAttrs:   string[];
}

// HTML global attributes per WHATWG §3.2.6 — apply to every element.
// `data-*`, `aria-*`, and `on*` event handler prefixes are recognised
// at the validator level (`Cribrum.Html.Model.isAllowedAttrName`).
export const GLOBAL_ATTRS: string[] = [
  "accesskey",  "autocapitalize", "autofocus",  "class",
  "contenteditable", "dir", "draggable", "enterkeyhint",
  "hidden", "id", "inert", "inputmode", "is", "itemid",
  "itemprop", "itemref", "itemscope", "itemtype", "lang",
  "nonce", "popover", "role", "slot", "spellcheck", "style",
  "tabindex", "title", "translate",
];

// Rows sorted lexicographically by `name` — determinism for I7
// (byte-identical regeneration). Adding an element: insert in sorted
// position.
export const CONTENT_MODEL: ContentModelRow[] = [
  { name: "a", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Interactive", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["href", "target", "download", "ping", "rel", "hreflang", "type", "referrerpolicy"] },
  { name: "abbr", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "address", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "area", isVoid: true, isRawText: false,
    categories: ["Flow", "Phrasing"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["alt", "coords", "shape", "href", "target", "download", "ping", "rel", "referrerpolicy"] },
  { name: "article", isVoid: false, isRawText: false,
    categories: ["Flow", "Sectioning", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "aside", isVoid: false, isRawText: false,
    categories: ["Flow", "Sectioning", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "audio", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Interactive"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["src", "crossorigin", "preload", "autoplay", "loop", "muted", "controls"] },
  { name: "b", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "base", isVoid: true, isRawText: false,
    categories: ["Metadata"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["href", "target"] },
  { name: "bdi", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "bdo", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["dir"] },
  { name: "blockquote", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: ["cite"] },
  { name: "body", isVoid: false, isRawText: false,
    categories: ["Flow"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [
      "onafterprint", "onbeforeprint", "onbeforeunload", "onhashchange",
      "onlanguagechange", "onmessage", "onmessageerror", "onoffline",
      "ononline", "onpagehide", "onpageshow", "onpopstate",
      "onrejectionhandled", "onstorage", "onunhandledrejection", "onunload",
    ] },
  { name: "br", isVoid: true, isRawText: false,
    categories: ["Flow", "Phrasing"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: [] },
  { name: "button", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Interactive", "FormAssociated", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["disabled", "form", "formaction", "formenctype", "formmethod",
                 "formnovalidate", "formtarget", "name", "popovertarget",
                 "popovertargetaction", "type", "value"] },
  { name: "canvas", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["width", "height"] },
  { name: "caption", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "cite", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "code", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "col", isVoid: true, isRawText: false,
    categories: [],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["span"] },
  { name: "colgroup", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyTags", tags: ["col", "template"], allowText: false },
    localAttrs: ["span"] },
  { name: "data", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["value"] },
  { name: "datalist", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: [] },
  { name: "dd", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "del", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["cite", "datetime"] },
  { name: "details", isVoid: false, isRawText: false,
    categories: ["Flow", "Interactive", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["open", "name"] },
  { name: "dfn", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "dialog", isVoid: false, isRawText: false,
    categories: ["Flow"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: ["open"] },
  { name: "div", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "dl", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyTags", tags: ["dt", "dd", "div", "script", "template"], allowText: false },
    localAttrs: [] },
  { name: "dt", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "em", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "embed", isVoid: true, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Interactive", "Palpable"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["src", "type", "width", "height"] },
  { name: "fieldset", isVoid: false, isRawText: false,
    categories: ["Flow", "FormAssociated", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["disabled", "form", "name"] },
  { name: "figcaption", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "figure", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: [] },
  { name: "footer", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "form", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: ["accept-charset", "action", "autocomplete", "enctype", "method",
                 "name", "novalidate", "rel", "target"] },
  { name: "h1", isVoid: false, isRawText: false,
    categories: ["Flow", "Heading", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "h2", isVoid: false, isRawText: false,
    categories: ["Flow", "Heading", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "h3", isVoid: false, isRawText: false,
    categories: ["Flow", "Heading", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "h4", isVoid: false, isRawText: false,
    categories: ["Flow", "Heading", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "h5", isVoid: false, isRawText: false,
    categories: ["Flow", "Heading", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "h6", isVoid: false, isRawText: false,
    categories: ["Flow", "Heading", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "head", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyTags",
                   tags: ["base", "link", "meta", "noscript", "script", "style", "template", "title"],
                   allowText: false },
    localAttrs: [] },
  { name: "header", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "hgroup", isVoid: false, isRawText: false,
    categories: ["Flow", "Heading", "Palpable"],
    childPolicy: { kind: "OnlyTags", tags: ["h1", "h2", "h3", "h4", "h5", "h6", "p"], allowText: false },
    localAttrs: [] },
  { name: "hr", isVoid: true, isRawText: false,
    categories: ["Flow"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: [] },
  { name: "html", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyTags", tags: ["head", "body"], allowText: false },
    localAttrs: ["xmlns"] },
  { name: "i", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "iframe", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Interactive", "Palpable"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["src", "srcdoc", "name", "sandbox", "allow", "allowfullscreen",
                 "width", "height", "referrerpolicy", "loading"] },
  { name: "img", isVoid: true, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Palpable"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["alt", "src", "srcset", "sizes", "crossorigin", "usemap",
                 "ismap", "width", "height", "referrerpolicy", "decoding",
                 "loading", "fetchpriority"] },
  { name: "input", isVoid: true, isRawText: false,
    categories: ["Flow", "Phrasing", "Interactive", "FormAssociated", "Palpable"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["accept", "alt", "autocomplete", "checked", "dirname",
                 "disabled", "form", "formaction", "formenctype", "formmethod",
                 "formnovalidate", "formtarget", "height", "list", "max", "maxlength",
                 "min", "minlength", "multiple", "name", "pattern", "placeholder",
                 "readonly", "required", "size", "src", "step", "type", "value",
                 "width"] },
  { name: "ins", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["cite", "datetime"] },
  { name: "kbd", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "label", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Interactive", "Palpable", "FormAssociated"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["for"] },
  { name: "legend", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing", "Heading"] },
    localAttrs: [] },
  { name: "li", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: ["value"] },
  { name: "link", isVoid: true, isRawText: false,
    categories: ["Metadata"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["href", "crossorigin", "rel", "media", "integrity", "hreflang",
                 "type", "referrerpolicy", "sizes", "imagesrcset", "imagesizes",
                 "as", "blocking", "color", "disabled", "fetchpriority"] },
  { name: "main", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "map", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["name"] },
  { name: "mark", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "math", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: [] },
  { name: "menu", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyTags", tags: ["li", "script", "template"], allowText: false },
    localAttrs: [] },
  { name: "meta", isVoid: true, isRawText: false,
    categories: ["Metadata"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["name", "http-equiv", "content", "charset", "media"] },
  { name: "meter", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "FormAssociated", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["value", "min", "max", "low", "high", "optimum"] },
  { name: "nav", isVoid: false, isRawText: false,
    categories: ["Flow", "Sectioning", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "noscript", isVoid: false, isRawText: false,
    categories: ["Metadata", "Flow", "Phrasing"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: [] },
  { name: "object", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["data", "type", "name", "form", "width", "height"] },
  { name: "ol", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyTags", tags: ["li", "script", "template"], allowText: false },
    localAttrs: ["reversed", "start", "type"] },
  { name: "optgroup", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyTags", tags: ["option", "script", "template"], allowText: false },
    localAttrs: ["disabled", "label"] },
  { name: "option", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "TextOnly" },
    localAttrs: ["disabled", "label", "selected", "value"] },
  { name: "output", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "FormAssociated", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["for", "form", "name"] },
  { name: "p", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "picture", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded"],
    childPolicy: { kind: "OnlyTags", tags: ["source", "img", "script", "template"], allowText: false },
    localAttrs: [] },
  { name: "pre", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "progress", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "FormAssociated", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["value", "max"] },
  { name: "q", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["cite"] },
  { name: "rp", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "TextOnly" },
    localAttrs: [] },
  { name: "rt", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "ruby", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: [] },
  { name: "s", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "samp", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "script", isVoid: false, isRawText: true,
    categories: ["Metadata", "Flow", "Phrasing", "ScriptSupporting"],
    childPolicy: { kind: "TextOnly" },
    localAttrs: ["src", "type", "nomodule", "async", "defer", "crossorigin",
                 "integrity", "referrerpolicy", "blocking", "fetchpriority"] },
  { name: "search", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "section", isVoid: false, isRawText: false,
    categories: ["Flow", "Sectioning", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: [] },
  { name: "select", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Interactive", "FormAssociated", "Palpable"],
    childPolicy: { kind: "OnlyTags", tags: ["option", "optgroup", "hr", "script", "template"], allowText: false },
    localAttrs: ["autocomplete", "disabled", "form", "multiple", "name",
                 "required", "size"] },
  { name: "slot", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["name"] },
  { name: "small", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "source", isVoid: true, isRawText: false,
    categories: [],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["type", "media", "src", "srcset", "sizes", "width", "height"] },
  { name: "span", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "strong", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "style", isVoid: false, isRawText: true,
    categories: ["Metadata"],
    childPolicy: { kind: "TextOnly" },
    localAttrs: ["media", "blocking"] },
  { name: "sub", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "summary", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing", "Heading"] },
    localAttrs: [] },
  { name: "sup", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "svg", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: [] },
  { name: "table", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyTags",
                   tags: ["caption", "colgroup", "thead", "tbody", "tfoot", "tr", "script", "template"],
                   allowText: false },
    localAttrs: [] },
  { name: "tbody", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyTags", tags: ["tr", "script", "template"], allowText: false },
    localAttrs: [] },
  { name: "td", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: ["colspan", "rowspan", "headers"] },
  { name: "template", isVoid: false, isRawText: false,
    categories: ["Metadata", "Flow", "Phrasing", "ScriptSupporting"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["shadowrootmode", "shadowrootdelegatesfocus", "shadowrootclonable"] },
  { name: "textarea", isVoid: false, isRawText: true,
    categories: ["Flow", "Phrasing", "Interactive", "FormAssociated", "Palpable"],
    childPolicy: { kind: "TextOnly" },
    localAttrs: ["autocomplete", "cols", "dirname", "disabled", "form", "maxlength",
                 "minlength", "name", "placeholder", "readonly", "required", "rows",
                 "wrap"] },
  { name: "tfoot", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyTags", tags: ["tr", "script", "template"], allowText: false },
    localAttrs: [] },
  { name: "th", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyCategories", cats: ["Flow"] },
    localAttrs: ["colspan", "rowspan", "headers", "scope", "abbr"] },
  { name: "thead", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyTags", tags: ["tr", "script", "template"], allowText: false },
    localAttrs: [] },
  { name: "time", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: ["datetime"] },
  { name: "title", isVoid: false, isRawText: false,
    categories: ["Metadata"],
    childPolicy: { kind: "TextOnly" },
    localAttrs: [] },
  { name: "tr", isVoid: false, isRawText: false,
    categories: [],
    childPolicy: { kind: "OnlyTags", tags: ["td", "th", "script", "template"], allowText: false },
    localAttrs: [] },
  { name: "track", isVoid: true, isRawText: false,
    categories: [],
    childPolicy: { kind: "NoChildren" },
    localAttrs: ["kind", "src", "srclang", "label", "default"] },
  { name: "u", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "ul", isVoid: false, isRawText: false,
    categories: ["Flow", "Palpable"],
    childPolicy: { kind: "OnlyTags", tags: ["li", "script", "template"], allowText: false },
    localAttrs: [] },
  { name: "var", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Palpable"],
    childPolicy: { kind: "OnlyCategories", cats: ["Phrasing"] },
    localAttrs: [] },
  { name: "video", isVoid: false, isRawText: false,
    categories: ["Flow", "Phrasing", "Embedded", "Interactive", "Palpable"],
    childPolicy: { kind: "AnyContent" },
    localAttrs: ["src", "crossorigin", "poster", "preload", "autoplay",
                 "playsinline", "loop", "muted", "controls", "width", "height"] },
  { name: "wbr", isVoid: true, isRawText: false,
    categories: ["Flow", "Phrasing"],
    childPolicy: { kind: "NoChildren" },
    localAttrs: [] },
];
