||| `render-docsnav` — close plan §T6.
|||
||| Drives the Cribrum pipeline end-to-end for the docs-nav demo:
|||
|||   README.dj
|||     -> parseDoc  (Cribrum.Djot.Parser)
|||     -> elaborate (Cribrum.Elaborate, strict)
|||     -> addHeadingIds (Cribrum.Pipeline.Anchor)
|||     -> renderHtml (Cribrum.Render.Html) over the unwrapped body
|||     -> harvestHeadings -> Generated.idr (TOC items, h2+h3 only)
|||     -> page chrome wrap -> examples/teaweb/docsnav/index.html
|||
||| Replaces the previously hand-authored static HTML + hand-coded TOC.
||| Anchors are slugified from the heading text; in-page navigation now
||| works without manual sync because the TOC links and the heading ids
||| come from the same `slugify` function.
module Main

import System
import System.File
import Data.List
import Data.String
import Cribrum.Node
import Cribrum.Djot.Surface
import Cribrum.Djot.Parser
import Cribrum.Html.Valid
import Cribrum.Elaborate
import Cribrum.Render.Html
import Cribrum.Pipeline.Anchor

%default total

--------------------------------------------------------------------------------
-- Pipeline.
--------------------------------------------------------------------------------

||| Strip the outer `<main>` wrapper inserted by `elaborateDoc` so the body
||| can compose into the docsnav page chrome (which has its own
||| `<main class="docs-content">`). For anything else, render as-is.
unwrapMain : HExpr -> List HExpr
unwrapMain (Element "main" _ cs) = cs
unwrapMain h                     = [h]

renderBody : HExpr -> String
renderBody h = concatMap renderHtml (unwrapMain h)

||| End-to-end: parse + elaborate + anchor + render-body, plus harvest
||| the heading rows for the TOC.
processSource :  String
              -> Either String (String, List (Nat, String, String))
processSource src = case parseDoc src of
  Left e  => Left ("parse failed: " ++ show e)
  Right d => case elaborate d of
    Left e             => Left ("elaborate failed: " ++ show e)
    Right (h ** (_, _)) =>
      let h2  = addHeadingIds h
          bod = renderBody h2
          hs  = harvestHeadings h2
       in Right (bod, hs)

--------------------------------------------------------------------------------
-- TOC filtering: keep h2 + h3 only, map level so h2 -> 1, h3 -> 2.
-- The page's `<h1>` is the document title, displayed separately above the
-- TOC, so it doesn't appear in the side-pane list.
--------------------------------------------------------------------------------

tocLevel : Nat -> Maybe Nat
tocLevel 2 = Just 1
tocLevel 3 = Just 2
tocLevel _ = Nothing

tocRows : List (Nat, String, String) -> List (Nat, String, String)
tocRows = mapMaybe go
  where
    go : (Nat, String, String) -> Maybe (Nat, String, String)
    go (lvl, anchor, title) = case tocLevel lvl of
      Just l  => Just (l, anchor, title)
      Nothing => Nothing

--------------------------------------------------------------------------------
-- Generated.idr emitter.
--------------------------------------------------------------------------------

escapeIdrisString : String -> String
escapeIdrisString = pack . concatMap esc . unpack
  where
    esc : Char -> List Char
    esc '\\' = ['\\', '\\']
    esc '"'  = ['\\', '"']
    esc c    = [c]

linePrefix : Bool -> String
linePrefix True  = "  [ "
linePrefix False = "  , "

tocItemLine : Bool -> (Nat, String, String) -> String
tocItemLine isFirst (lvl, anchor, title) =
  linePrefix isFirst
    ++ "MkTocItem \""
    ++ escapeIdrisString anchor
    ++ "\" \""
    ++ escapeIdrisString title
    ++ "\" "
    ++ show lvl
    ++ "\n"

renderTocList : List (Nat, String, String) -> String
renderTocList []        = "  []\n"
renderTocList (r :: rs) =
  tocItemLine True r
    ++ concatMap (tocItemLine False) rs
    ++ "  ]\n"

emitGenerated : List (Nat, String, String) -> String
emitGenerated items =
  "||| AUTO-GENERATED by tools/render-docsnav — do not edit by hand.\n"
    ++ "|||\n"
    ++ "||| Source: README.dj headings (h2 -> TocItem level 1, h3 -> level 2).\n"
    ++ "||| Anchors are slugified from heading text by `Cribrum.Pipeline.Anchor`,\n"
    ++ "||| so they match the `id` attributes the same pipeline writes onto the\n"
    ++ "||| corresponding `<h2>`/`<h3>` elements in `index.html`.\n"
    ++ "module Generated\n\n"
    ++ "import TocData\n\n"
    ++ "%default total\n\n"
    ++ "public export\n"
    ++ "genTocItems : List TocItem\n"
    ++ "genTocItems =\n"
    ++ renderTocList items

--------------------------------------------------------------------------------
-- Page chrome — copied verbatim from the previous hand-authored
-- `index.html`, minus the static prose (now driven by README.dj) and the
-- mount-point `<main>` (replaced with `<div>` to avoid two `<main>`
-- elements in the final document, which would violate `unique-main`).
--------------------------------------------------------------------------------

chromeHeadAndOpen : String
chromeHeadAndOpen = """
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cribrum docs — TEAWeb T6 demo</title>
    <style>
      :root {
        --bg:          #fdfcf8;
        --fg:          #1c1b18;
        --muted:       #6b6862;
        --accent:      #1059a4;
        --highlight:   #fff4c0;
        --border:      #d9d6cf;
        --code-bg:     #f0eee8;
      }
      * { box-sizing: border-box; }
      html, body {
        margin: 0;
        background: var(--bg);
        color: var(--fg);
        font-family: ui-serif, Georgia, serif;
        line-height: 1.55;
      }
      .docs-shell {
        display: grid;
        grid-template-columns: 18rem 1fr;
        gap: 2rem;
        max-width: 72rem;
        margin: 0 auto;
        padding: 2rem 1.5rem;
      }
      aside.docs-sidebar {
        position: sticky;
        top: 2rem;
        align-self: start;
        max-height: calc(100vh - 4rem);
        overflow: auto;
      }
      main.docs-content {
        min-width: 0;
      }
      main.docs-content > :first-child { margin-top: 0; }
      h1, h2, h3 {
        font-family: ui-sans-serif, system-ui, sans-serif;
        margin-top: 2rem;
      }
      h1 { font-size: 1.75rem; }
      h2 { font-size: 1.35rem; padding-top: 0.25rem; border-top: 1px solid var(--border); }
      h3 { font-size: 1.05rem; }
      pre, code { font-family: ui-monospace, "JetBrains Mono", monospace; }
      pre {
        background: var(--code-bg);
        padding: 0.75rem 1rem;
        border-radius: 0.25rem;
        overflow: auto;
      }
      code { background: var(--code-bg); padding: 0.05rem 0.25rem; border-radius: 0.2rem; }
      pre code { background: transparent; padding: 0; }

      /* TEAWeb island styling */
      .docsnav-island {
        border: 1px solid var(--border);
        border-radius: 0.5rem;
        background: white;
        padding: 1rem;
        font-family: ui-sans-serif, system-ui, sans-serif;
        font-size: 0.95rem;
      }
      .docsnav-header h2 {
        margin: 0 0 0.25rem;
        font-size: 1.05rem;
        border: none;
        padding: 0;
      }
      .docsnav-help {
        margin: 0;
        font-size: 0.78rem;
        color: var(--muted);
      }
      .docsnav-search {
        display: flex;
        gap: 0.5rem;
        margin: 0.75rem 0;
      }
      .docsnav-search input {
        flex: 1;
        padding: 0.4rem 0.5rem;
        border: 1px solid var(--border);
        border-radius: 0.25rem;
        font-size: inherit;
      }
      .docsnav-search input:focus { outline: 2px solid var(--accent); outline-offset: -1px; }
      .docsnav-search button {
        padding: 0.4rem 0.7rem;
        border: 1px solid var(--border);
        border-radius: 0.25rem;
        background: var(--bg);
        cursor: pointer;
      }
      .docsnav-list {
        list-style: none;
        padding: 0;
        margin: 0.25rem 0 0.75rem;
        max-height: 24rem;
        overflow: auto;
      }
      .toc-item {
        line-height: 1.4;
        padding: 0;
      }
      .toc-item a {
        display: block;
        padding: 0.25rem 0.5rem;
        color: var(--fg);
        text-decoration: none;
        border-radius: 0.2rem;
      }
      .toc-l2 a { padding-left: 1.5rem; font-size: 0.9rem; color: var(--muted); }
      .toc-item.selected a {
        background: var(--highlight);
        color: var(--fg);
        outline: 1px solid var(--accent);
      }
      .toc-item a:hover { background: #f3efe2; }
      .docsnav-empty {
        margin: 0.5rem 0;
        font-style: italic;
        color: var(--muted);
      }
      .docsnav-status {
        margin: 0;
        font-size: 0.78rem;
        color: var(--muted);
        border-top: 1px solid var(--border);
        padding-top: 0.4rem;
      }
    </style>
  </head>
  <body>
    <div class="docs-shell">
      <aside class="docs-sidebar">
        <!-- The interactive TEAWeb island mounts here. -->
        <div id="toc-island"></div>
      </aside>

      <main class="docs-content">
"""

chromeClose : String
chromeClose = """
      </main>
    </div>
    <script src="build/exec/docsnav"></script>
  </body>
</html>
"""

wrapDocsnavPage : String -> String
wrapDocsnavPage body = chromeHeadAndOpen ++ body ++ "\n" ++ chromeClose

--------------------------------------------------------------------------------
-- IO plumbing.
--------------------------------------------------------------------------------

covering
readOrFail : String -> IO String
readOrFail path = do
  Right s <- readFile path
    | Left err => do
        putStrLn ("read error (" ++ path ++ "): " ++ show err)
        exitFailure
  pure s

covering
writeOrFail : String -> String -> IO ()
writeOrFail path contents = do
  Right () <- writeFile path contents
    | Left err => do
        putStrLn ("write error (" ++ path ++ "): " ++ show err)
        exitFailure
  pure ()

covering
main : IO ()
main = do
  args <- getArgs
  case args of
    [_, dj, html, gen] => do
      src <- readOrFail dj
      case processSource src of
        Left err =>
          do putStrLn err
             exitFailure
        Right (body, headings) => do
          let toc = tocRows headings
          writeOrFail html (wrapDocsnavPage body)
          writeOrFail gen  (emitGenerated toc)
          putStrLn $ "wrote " ++ html ++ " (" ++ show (length body)
                      ++ " body bytes, " ++ show (length toc)
                      ++ " TOC entries)"
          putStrLn $ "wrote " ++ gen
    _ => do
      putStrLn "usage: render-docsnav <README.dj> <index.html> <Generated.idr>"
      exitFailure
