||| AUTO-GENERATED by ingest/aa-catalog.ts — do not edit by hand.
||| aa.ts: sha256 d24cec1614869a37a51c323f74af67111c8f8e1da174f5d6ba0766f4cc2e2dab
||| catalog hash: sha256 2a92370d31aa6cb0e92c6df26ac50b0399cf7a9dac2a9810b703dd54608684b2
module Cribrum.AA.Catalog.Generated

import Cribrum.AA.Catalog.Types

%default total

--------------------------------------------------------------------------------
-- Per-rule constants.
--------------------------------------------------------------------------------

public export
ruleActAriaStateOrPropertyHasValidValue6a7281 : Rule
ruleActAriaStateOrPropertyHasValidValue6a7281 = MkRule
  { id            = "act-aria-state-or-property-has-valid-value-6a7281"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "ARIA state or property has valid value"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "6a7281"
  , ruleType      = "atomic"
  , wcagAll       = []
  , applicability = "This rule applies to any WAI-ARIA state or property that has a non-empty (\"\") attribute value, and that is specified on an HTML or SVG element."
  , expectation   = "Each test target has an attribute value that is valid according to its WAI-ARIA value type. Exception: For value types ID Reference and ID Reference List no ID referenced elements are required."
  }

public export
ruleActAttributeIsNotDuplicatedE6952f : Rule
ruleActAttributeIsNotDuplicatedE6952f = MkRule
  { id            = "act-attribute-is-not-duplicated-e6952f"
  , wcag          = "4.1.1"
  , level         = "A"
  , title         = "Attribute is not duplicated"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "e6952f"
  , ruleType      = "atomic"
  , wcagAll       = ["4.1.1"]
  , applicability = "This rule applies to any starting tag in an HTML or SVG document. Note: This rule cannot be tested on the DOM Tree because the browser removes duplicates of any attribute that is already present on an element."
  , expectation   = "For each test target, there are no duplicated attributes."
  }

public export
ruleActAutocompleteAttributeHasValidValue73f2c2 : Rule
ruleActAutocompleteAttributeHasValidValue73f2c2 = MkRule
  { id            = "act-autocomplete-attribute-has-valid-value-73f2c2"
  , wcag          = "1.3.5"
  , level         = "AA"
  , title         = "Autocomplete attribute has valid value"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "73f2c2"
  , ruleType      = "atomic"
  , wcagAll       = ["1.3.5"]
  , applicability = "This rule applies to any HTML input, select and textarea element with an autocomplete attribute value that is neither empty (\"\") nor only ASCII whitespace, except if one or more of the following is true: <dfn id=\"73f2c2:toggle\">toggle</dfn>: the autocomplete attribute consists of a single token that is an ASCII case-insensitive match for the string off or the string on; or <dfn id=\"73f2c2:disabled\">disabled</dfn>: the element is a [disabled element]; or <dfn id=\"73f2c2:fixed-value\">fixed value</dfn>: the element is an input element with a type attribute value of button, checkbox, file, image,…"
  , expectation   = "Each test target's autocomplete attribute value is a space separated list of one or more tokens that follow the HTML specification for Autofill detail tokens, which requires that the token list match the following in the correct order: 1. An optional token that starts with \"section-\"; then 2. An optional token of either \"shipping\" or \"billing\"; then 3. An optional token of either \"home\", \"work\", \"mobile\", \"fax\" or \"pager\", only if the next token is \"email\", \"impp\", \"tel\" or \"tel-\\\"; then 4. A required token from the correct autocomplete field; then 5. An optional \"webauthn\" token."
  }

public export
ruleActButtonHasNonEmptyAccessibleName97a4e1 : Rule
ruleActButtonHasNonEmptyAccessibleName97a4e1 = MkRule
  { id            = "act-button-has-non-empty-accessible-name-97a4e1"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "Button has non-empty accessible name"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "97a4e1"
  , ruleType      = "atomic"
  , wcagAll       = ["4.1.2"]
  , applicability = "This rule applies to elements that are included in the accessibility tree and have a semantic role of button, except for input elements with a type [attribute value] of image."
  , expectation   = "Each target element has an accessible name that is not empty (\"\")."
  }

public export
ruleActFormFieldHasNonEmptyAccessibleNameE086e5 : Rule
ruleActFormFieldHasNonEmptyAccessibleNameE086e5 = MkRule
  { id            = "act-form-field-has-non-empty-accessible-name-e086e5"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "Form field has non-empty accessible name"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "e086e5"
  , ruleType      = "atomic"
  , wcagAll       = ["4.1.2"]
  , applicability = "This rule applies to any element that is included in the accessibility tree and for which one of the following is true: the element has one of the following semantic roles: checkbox, combobox (select elements), listbox, menuitemcheckbox, menuitemradio, radio, searchbox, slider, spinbutton, switch, textbox; or the element is an input with no semantic role and a type attribute value of color, date, datetime-local, file, month, password, time, or week."
  , expectation   = "Each target element has an accessible name that is not empty (\"\")."
  }

public export
ruleActHtmlPageHasLangAttributeB5c3f8 : Rule
ruleActHtmlPageHasLangAttributeB5c3f8 = MkRule
  { id            = "act-html-page-has-lang-attribute-b5c3f8"
  , wcag          = "3.1.1"
  , level         = "A"
  , title         = "HTML page has lang attribute"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "b5c3f8"
  , ruleType      = "atomic"
  , wcagAll       = ["3.1.1"]
  , applicability = "This rule applies to any document element if it is an html element for which all the following are true: is in a top-level browsing context; and has a node document with a content type of text/html. Note: html elements within iframe and object elements are not applicable as iframe and object elements create nested browsing contexts. However, as these elements are meant to provide a layer of isolation, the declared language of their parent browsing context will likely not be inherited, making it possible for empty lang attributes in nested browsing contexts to also cause accessibility issues."
  , expectation   = "Each test target has a lang attribute value that is neither empty (\"\") nor only ASCII whitespace."
  }

public export
ruleActHtmlPageHasNonEmptyTitle2779a5 : Rule
ruleActHtmlPageHasNonEmptyTitle2779a5 = MkRule
  { id            = "act-html-page-has-non-empty-title-2779a5"
  , wcag          = "2.4.2"
  , level         = "A"
  , title         = "HTML page has non-empty title"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "2779a5"
  , ruleType      = "atomic"
  , wcagAll       = ["2.4.2"]
  , applicability = "This rule applies to the root element of the web page, if it is an html element."
  , expectation   = ""
  }

public export
ruleActIdAttributeValueIsUnique3ea0c8 : Rule
ruleActIdAttributeValueIsUnique3ea0c8 = MkRule
  { id            = "act-id-attribute-value-is-unique-3ea0c8"
  , wcag          = "4.1.1"
  , level         = "A"
  , title         = "Id attribute value is unique"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "3ea0c8"
  , ruleType      = "atomic"
  , wcagAll       = ["4.1.1"]
  , applicability = "This rule applies to any id attribute whose value is not an empty string (\"\"), specified on a HTML or SVG element. Note: Elements that are neither included in the accessibility tree nor visible are still considered for this rule."
  , expectation   = "The value of the attribute is unique across all other id attributes specified on HTML or SVG elements that exist within the same document tree or shadow tree as the element on which the applicable id attribute is specified."
  }

public export
ruleActIframeElementHasNonEmptyAccessibleNameCae760 : Rule
ruleActIframeElementHasNonEmptyAccessibleNameCae760 = MkRule
  { id            = "act-iframe-element-has-non-empty-accessible-name-cae760"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "Iframe element has non-empty accessible name"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "cae760"
  , ruleType      = "atomic"
  , wcagAll       = ["4.1.2"]
  , applicability = "This rule applies to iframe elements that are included in the accessibility tree except if at least one of the following is true: the iframe has a negative tabindex attribute value; or the iframe is marked as decorative."
  , expectation   = "Each target element has an accessible name that is not empty (\"\")."
  }

public export
ruleActImageButtonHasNonEmptyAccessibleName59796f : Rule
ruleActImageButtonHasNonEmptyAccessibleName59796f = MkRule
  { id            = "act-image-button-has-non-empty-accessible-name-59796f"
  , wcag          = "1.1.1"
  , level         = "A"
  , title         = "Image button has non-empty accessible name"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "59796f"
  , ruleType      = "atomic"
  , wcagAll       = ["1.1.1", "4.1.2"]
  , applicability = "This rule applies to any input element with a type attribute value of image, and that is included in the accessibility tree."
  , expectation   = "Each target element has an accessible name that is neither empty (\"\"), nor the default name for this element (localized version of \"Submit Query\")."
  }

public export
ruleActImageHasNonEmptyAccessibleName23a2a8 : Rule
ruleActImageHasNonEmptyAccessibleName23a2a8 = MkRule
  { id            = "act-image-has-non-empty-accessible-name-23a2a8"
  , wcag          = "1.1.1"
  , level         = "AA"
  , title         = "Image has non-empty accessible name"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "23a2a8"
  , ruleType      = "atomic"
  , wcagAll       = ["1.1.1"]
  , applicability = "This rule applies to HTML img elements and HTML elements that are a semantic img, except if the element is programmatically hidden."
  , expectation   = "Each target element has an accessible name that is not empty (\"\"), or has a semantic role of none or presentation."
  }

public export
ruleActLinkHasNonEmptyAccessibleNameC487ae : Rule
ruleActLinkHasNonEmptyAccessibleNameC487ae = MkRule
  { id            = "act-link-has-non-empty-accessible-name-c487ae"
  , wcag          = "2.4.4"
  , level         = "A"
  , title         = "Link has non-empty accessible name"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "c487ae"
  , ruleType      = "atomic"
  , wcagAll       = ["2.4.4", "2.4.9", "4.1.2"]
  , applicability = "This rule applies to any HTML element that is an inheriting semantic link included in the accessibility tree."
  , expectation   = "Each target element has an accessible name that is not empty (\"\")."
  }

public export
ruleActMetaViewportAllowsForZoomB4f0c3 : Rule
ruleActMetaViewportAllowsForZoomB4f0c3 = MkRule
  { id            = "act-meta-viewport-allows-for-zoom-b4f0c3"
  , wcag          = "1.4.4"
  , level         = "AA"
  , title         = "Meta viewport allows for zoom"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "b4f0c3"
  , ruleType      = "atomic"
  , wcagAll       = ["1.4.4"]
  , applicability = "This rule applies to each content attribute for which all of the following are true: the attribute is defined on a meta element with a name attribute value of viewport; and the attribute value has at least one of the maximum-scale or user-scalable keys. For the purpose of this rule, the attribute value of the content attribute is a list of key/value pairs."
  , expectation   = ""
  }

public export
ruleActObjectElementRenderingNonTextContentHasNonEmptyAccessibleName8fc3b6 : Rule
ruleActObjectElementRenderingNonTextContentHasNonEmptyAccessibleName8fc3b6 = MkRule
  { id            = "act-object-element-rendering-non-text-content-has-non-empty-accessible-name-8fc3b6"
  , wcag          = "1.1.1"
  , level         = "A"
  , title         = "Object element rendering non-text content has non-empty accessible name"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "8fc3b6"
  , ruleType      = "atomic"
  , wcagAll       = ["1.1.1"]
  , applicability = "This rule applies to any object element for which all the following are true: The object element is included in the accessibility tree; and The object element has no explicit role; and The object element embeds a resource whose MIME type is either image, or audio or video."
  , expectation   = "Each target element has an accessible name that is not empty (\"\")."
  }

public export
ruleActRoleAttributeHasValidValue674b10 : Rule
ruleActRoleAttributeHasValidValue674b10 = MkRule
  { id            = "act-role-attribute-has-valid-value-674b10"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "Role attribute has valid value"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "674b10"
  , ruleType      = "atomic"
  , wcagAll       = []
  , applicability = "This rule applies to any role attribute for which all the following are true: the attribute has a value that is neither empty (\"\") nor only ASCII whitespace; and the attribute is specified on an HTML or SVG element which is not programmatically hidden."
  , expectation   = "Each test target has at least one token which is a valid value corresponding to a non-abstract role from WAI-ARIA Specifications."
  }

public export
ruleActSummaryElementHasNonEmptyAccessibleName2t702h : Rule
ruleActSummaryElementHasNonEmptyAccessibleName2t702h = MkRule
  { id            = "act-summary-element-has-non-empty-accessible-name-2t702h"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "Summary element has non-empty accessible name"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Act
  , actId         = "2t702h"
  , ruleType      = "atomic"
  , wcagAll       = ["4.1.2"]
  , applicability = "This rule applies to HTML summary elements for which all the following are true: the element is included in the accessibility tree; and the element works as the summary button for its parent details element; and the element has no explicit role, or the explicit role is ignored due to a presentational role conflict."
  , expectation   = "Each target element has an accessible name that is not empty (\"\"), nor just the name of the ::marker pseudo element."
  }

public export
ruleAltMeaningful : Rule
ruleAltMeaningful = MkRule
  { id            = "alt-meaningful"
  , wcag          = "1.1.1"
  , level         = "A"
  , title         = "`alt` text must be meaningful (not just filename or empty)"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleAnchorHref : Rule
ruleAnchorHref = MkRule
  { id            = "anchor-href"
  , wcag          = "2.4.4"
  , level         = "A"
  , title         = "Anchor (`<a>`) must have an `href` attribute"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleAreaAlt : Rule
ruleAreaAlt = MkRule
  { id            = "area-alt"
  , wcag          = "1.1.1"
  , level         = "A"
  , title         = "Each `<area>` with `href` must have an `alt` attribute"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleAriaHiddenBody : Rule
ruleAriaHiddenBody = MkRule
  { id            = "aria-hidden-body"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "`<body>` must not carry `aria-hidden=\"true\"` (hides the whole page from assistive tech)"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleAriaLabelRedundant : Rule
ruleAriaLabelRedundant = MkRule
  { id            = "aria-label-redundant"
  , wcag          = "4.1.2"
  , level         = "AA"
  , title         = "`aria-label` should not duplicate the element's visible text"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleAriaRoleValid : Rule
ruleAriaRoleValid = MkRule
  { id            = "aria-role-valid"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "A `role` attribute value must be a defined WAI-ARIA role token"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleAudioDescription : Rule
ruleAudioDescription = MkRule
  { id            = "audio-description"
  , wcag          = "1.2.5"
  , level         = "AA"
  , title         = "Audio Description (Prerecorded): synchronised audio description for prerecorded video"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Prerecorded synchronised-media video content."
  , expectation   = "An audio description track conveys the important visual information not in the main audio."
  }

public export
ruleAutocompleteValid : Rule
ruleAutocompleteValid = MkRule
  { id            = "autocomplete-valid"
  , wcag          = "1.3.5"
  , level         = "AA"
  , title         = "An `autocomplete` value must be a known token (or on/off)"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleButtonName : Rule
ruleButtonName = MkRule
  { id            = "button-name"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "Each `<button>` must have an accessible name (text content or `aria-label`)"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleCaptionFirstChild : Rule
ruleCaptionFirstChild = MkRule
  { id            = "caption-first-child"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "A `<table>` `<caption>`, if present, must be the table's first child"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleCaptionsLive : Rule
ruleCaptionsLive = MkRule
  { id            = "captions-live"
  , wcag          = "1.2.4"
  , level         = "AA"
  , title         = "Captions (Live): synchronised captions for all live synchronised-media audio"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Live synchronised-media audio content."
  , expectation   = "Real-time captions convey the live audio's speech and meaningful sounds."
  }

public export
ruleCharacterKeyShortcuts : Rule
ruleCharacterKeyShortcuts = MkRule
  { id            = "character-key-shortcuts"
  , wcag          = "2.1.4"
  , level         = "A"
  , title         = "Character Key Shortcuts: single-character shortcuts can be turned off, remapped, or are active only on focus"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Keyboard shortcuts implemented using only letter, punctuation, number, or symbol characters."
  , expectation   = "The shortcut can be disabled, remapped, or is active only while the relevant component has focus."
  }

public export
ruleConsistentIdentification : Rule
ruleConsistentIdentification = MkRule
  { id            = "consistent-identification"
  , wcag          = "3.2.4"
  , level         = "AA"
  , title         = "Consistent Identification: components with the same functionality are identified consistently across pages"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Components that have the same functionality within a set of web pages."
  , expectation   = "They are identified consistently (same accessible name / label across the set)."
  }

public export
ruleConsistentNavigation : Rule
ruleConsistentNavigation = MkRule
  { id            = "consistent-navigation"
  , wcag          = "3.2.3"
  , level         = "AA"
  , title         = "Consistent Navigation: repeated navigational mechanisms occur in the same relative order across pages"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Navigational mechanisms repeated across a set of web pages."
  , expectation   = "They occur in the same relative order each time, unless the user initiates a change."
  }

public export
ruleContentOnHoverFocus : Rule
ruleContentOnHoverFocus = MkRule
  { id            = "content-on-hover-focus"
  , wcag          = "1.4.13"
  , level         = "AA"
  , title         = "Content on Hover or Focus: additional content triggered by hover/focus is dismissable, hoverable, and persistent"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Content that becomes visible on pointer hover or keyboard focus and then hidden again."
  , expectation   = "The content is dismissable, hoverable, and persistent until dismissed or invalid."
  }

public export
ruleContrastMinimum : Rule
ruleContrastMinimum = MkRule
  { id            = "contrast-minimum"
  , wcag          = "1.4.3"
  , level         = "AA"
  , title         = "Contrast (Minimum): text has a contrast ratio of at least 4.5:1 (3:1 for large text)"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Text and images of text rendered to the user."
  , expectation   = "Contrast ratio is at least 4.5:1, or 3:1 for large-scale text; incidental and logotype text exempt."
  }

public export
ruleDocumentLang : Rule
ruleDocumentLang = MkRule
  { id            = "document-lang"
  , wcag          = "3.1.1"
  , level         = "A"
  , title         = "The `<html>` root must carry a non-empty `lang` attribute"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleDuplicateId : Rule
ruleDuplicateId = MkRule
  { id            = "duplicate-id"
  , wcag          = "4.1.1"
  , level         = "A"
  , title         = "No two elements may share the same `id`"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleErrorIdentification : Rule
ruleErrorIdentification = MkRule
  { id            = "error-identification"
  , wcag          = "3.3.1"
  , level         = "A"
  , title         = "Error Identification: input errors are detected and described to the user in text"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Form input errors that are automatically detected."
  , expectation   = "The erroneous item is identified and the error described to the user in text."
  }

public export
ruleErrorPreventionLegal : Rule
ruleErrorPreventionLegal = MkRule
  { id            = "error-prevention-legal"
  , wcag          = "3.3.4"
  , level         = "AA"
  , title         = "Error Prevention (Legal, Financial, Data): submissions are reversible, checked, or confirmable"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Pages causing legal commitments, financial transactions, or data modification/deletion."
  , expectation   = "Submissions are reversible, checked for errors, or confirmed before finalising."
  }

public export
ruleErrorSuggestion : Rule
ruleErrorSuggestion = MkRule
  { id            = "error-suggestion"
  , wcag          = "3.3.3"
  , level         = "AA"
  , title         = "Error Suggestion: known correction suggestions are provided when an input error is detected"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Input errors that are automatically detected and for which a correction is known."
  , expectation   = "Correction suggestions are provided unless they would jeopardise security or purpose."
  }

public export
ruleFieldsetLegend : Rule
ruleFieldsetLegend = MkRule
  { id            = "fieldset-legend"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "Each `<fieldset>` should contain a `<legend>` as its accessible name"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleFocusVisible : Rule
ruleFocusVisible = MkRule
  { id            = "focus-visible"
  , wcag          = "2.4.7"
  , level         = "AA"
  , title         = "Focus Visible: the keyboard focus indicator is visible"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "User-interface components operable by keyboard."
  , expectation   = "When a component has keyboard focus, a visible focus indicator is shown."
  }

public export
ruleHeadingNoSkip : Rule
ruleHeadingNoSkip = MkRule
  { id            = "heading-no-skip"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "Heading levels must not skip (e.g. h1 -> h3 disallowed)"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleIframeTitle : Rule
ruleIframeTitle = MkRule
  { id            = "iframe-title"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "Each `<iframe>` must have a non-empty `title` attribute"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleImagesOfText : Rule
ruleImagesOfText = MkRule
  { id            = "images-of-text"
  , wcag          = "1.4.5"
  , level         = "AA"
  , title         = "Images of Text: text is used in preference to images of text where the same presentation is possible"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Images that render text (excluding logotypes and essential presentations)."
  , expectation   = "Real text is used instead of an image of text unless the presentation is essential or customisable."
  }

public export
ruleImgAlt : Rule
ruleImgAlt = MkRule
  { id            = "img-alt"
  , wcag          = "1.1.1"
  , level         = "A"
  , title         = "Images must have an `alt` attribute"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleInputButtonName : Rule
ruleInputButtonName = MkRule
  { id            = "input-button-name"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "`<input type=\"button|submit|reset\">` must have a `value` or `aria-label`/`title` accessible name"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleInputImageAlt : Rule
ruleInputImageAlt = MkRule
  { id            = "input-image-alt"
  , wcag          = "1.1.1"
  , level         = "A"
  , title         = "`<input type=\"image\">` must have a non-empty `alt` attribute"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleKeyboard : Rule
ruleKeyboard = MkRule
  { id            = "keyboard"
  , wcag          = "2.1.1"
  , level         = "A"
  , title         = "Keyboard: all functionality is operable through a keyboard interface"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "All interactive functionality of the page."
  , expectation   = "Every function is operable via keyboard without requiring specific timings, except where the underlying task is path-dependent."
  }

public export
ruleLabelFor : Rule
ruleLabelFor = MkRule
  { id            = "label-for-control"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "Each `<label>` must have a `for` attribute or contain its control"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleLabelInName : Rule
ruleLabelInName = MkRule
  { id            = "label-in-name"
  , wcag          = "2.5.3"
  , level         = "A"
  , title         = "Label in Name: the accessible name of a control contains its visible label text"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Components with labels that include text or images of text."
  , expectation   = "The accessible name contains the text that is presented visually as the label."
  }

public export
ruleLinkEmptyHref : Rule
ruleLinkEmptyHref = MkRule
  { id            = "link-empty-href"
  , wcag          = "2.4.4"
  , level         = "A"
  , title         = "`<a href=\"\">` is ineffective and rejected"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleLinkName : Rule
ruleLinkName = MkRule
  { id            = "link-name"
  , wcag          = "2.4.4"
  , level         = "A"
  , title         = "Each `<a>` with `href` must have accessible text (text content or `aria-label`)"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleMetaNoRefresh : Rule
ruleMetaNoRefresh = MkRule
  { id            = "meta-no-refresh"
  , wcag          = "2.2.1"
  , level         = "A"
  , title         = "`<meta http-equiv=\"refresh\">` triggers an unsolicited timeout"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleMotionActuation : Rule
ruleMotionActuation = MkRule
  { id            = "motion-actuation"
  , wcag          = "2.5.4"
  , level         = "A"
  , title         = "Motion Actuation: functionality operated by device or user motion has a conventional control alternative"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Functionality triggered by device motion (e.g. shaking) or user motion (gestures)."
  , expectation   = "An equivalent UI-component control exists and the motion response can be disabled."
  }

public export
ruleNoEmptyHeading : Rule
ruleNoEmptyHeading = MkRule
  { id            = "no-empty-heading"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "Heading elements (`<h1>`..`<h6>`) must have a non-empty accessible name"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleNoKeyboardTrap : Rule
ruleNoKeyboardTrap = MkRule
  { id            = "no-keyboard-trap"
  , wcag          = "2.1.2"
  , level         = "A"
  , title         = "No Keyboard Trap: focus can be moved away from any component using only the keyboard"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Components that can receive keyboard focus."
  , expectation   = "Focus can be moved away using standard keyboard navigation, or the user is told how."
  }

public export
ruleNonTextContrast : Rule
ruleNonTextContrast = MkRule
  { id            = "non-text-contrast"
  , wcag          = "1.4.11"
  , level         = "AA"
  , title         = "Non-text Contrast: UI components and graphical objects have at least 3:1 contrast against adjacent colours"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "User-interface component states and meaningful graphical objects."
  , expectation   = "Contrast against adjacent colours is at least 3:1."
  }

public export
ruleObjectName : Rule
ruleObjectName = MkRule
  { id            = "object-name"
  , wcag          = "1.1.1"
  , level         = "A"
  , title         = "Each `<object>` must have an accessible name (text content, `aria-label`, or `title`)"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleOrientation : Rule
ruleOrientation = MkRule
  { id            = "orientation"
  , wcag          = "1.3.4"
  , level         = "AA"
  , title         = "Orientation: content does not restrict its view to a single display orientation unless essential"
  , confidence    = Runtime
  , severity      = Info
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Content with an operable view orientation."
  , expectation   = "Both portrait and landscape orientations are supported unless a specific orientation is essential."
  }

public export
rulePointerCancellation : Rule
rulePointerCancellation = MkRule
  { id            = "pointer-cancellation"
  , wcag          = "2.5.2"
  , level         = "A"
  , title         = "Pointer Cancellation: single-pointer actions can be aborted or undone (no down-event execution)"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Functionality operable with a single pointer."
  , expectation   = "No down-event activation, or completion is on up-event with abort/undo, or down-event is essential."
  }

public export
rulePointerGestures : Rule
rulePointerGestures = MkRule
  { id            = "pointer-gestures"
  , wcag          = "2.5.1"
  , level         = "A"
  , title         = "Pointer Gestures: multipoint or path-based gestures have a single-pointer alternative"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Functionality using multipoint or path-based gestures."
  , expectation   = "A single-pointer operation without a path-based gesture is also available, unless essential."
  }

public export
rulePositiveTabindex : Rule
rulePositiveTabindex = MkRule
  { id            = "positive-tabindex"
  , wcag          = "2.4.3"
  , level         = "A"
  , title         = "Positive `tabindex` values disrupt natural focus order"
  , confidence    = Heuristic
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleReflow : Rule
ruleReflow = MkRule
  { id            = "reflow"
  , wcag          = "1.4.10"
  , level         = "AA"
  , title         = "Reflow: content reflows to a single column at 320px width without two-dimensional scrolling"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Content presented at a viewport width of 320 CSS px (400% zoom of 1280px)."
  , expectation   = "No loss of content or function and no two-dimensional scrolling, except where essential."
  }

public export
ruleResizeText : Rule
ruleResizeText = MkRule
  { id            = "resize-text"
  , wcag          = "1.4.4"
  , level         = "AA"
  , title         = "Resize Text: text can be resized up to 200% without loss of content or functionality"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Text content (excluding captions and images of text)."
  , expectation   = "Resizing text up to 200% loses no content or functionality, without assistive technology."
  }

public export
ruleSelectHasOptions : Rule
ruleSelectHasOptions = MkRule
  { id            = "select-has-options"
  , wcag          = "4.1.2"
  , level         = "A"
  , title         = "A `<select>` must contain at least one `<option>` to be operable"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleStatusMessages : Rule
ruleStatusMessages = MkRule
  { id            = "status-messages"
  , wcag          = "4.1.3"
  , level         = "AA"
  , title         = "Status Messages: status messages are programmatically determinable without receiving focus"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Status messages that convey changes not associated with a focus change."
  , expectation   = "They are exposed via role or property (e.g. a live region) so assistive tech announces them without moving focus."
  }

public export
ruleSummaryNotEmpty : Rule
ruleSummaryNotEmpty = MkRule
  { id            = "summary-not-empty"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "`<details>` must contain a non-empty `<summary>` for accessible name"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleTextSpacing : Rule
ruleTextSpacing = MkRule
  { id            = "text-spacing"
  , wcag          = "1.4.12"
  , level         = "AA"
  , title         = "Text Spacing: no loss of content when line, paragraph, letter, and word spacing are overridden"
  , confidence    = Runtime
  , severity      = Warning
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = "Text whose spacing can be set by the user via style overrides."
  , expectation   = "No content or functionality is lost at line-height 1.5x, paragraph 2x, letter 0.12x, word 0.16x font size."
  }

public export
ruleThHasName : Rule
ruleThHasName = MkRule
  { id            = "th-has-name"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "Each table header cell (`<th>`) must have a non-empty accessible name"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleThScopeValid : Rule
ruleThScopeValid = MkRule
  { id            = "th-scope-valid"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "A `<th scope>` value must be one of row, col, rowgroup, colgroup"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleTrackKind : Rule
ruleTrackKind = MkRule
  { id            = "track-kind"
  , wcag          = "1.2.2"
  , level         = "A"
  , title         = "Each `<track>` must declare a `kind` attribute"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

public export
ruleUniqueMain : Rule
ruleUniqueMain = MkRule
  { id            = "unique-main"
  , wcag          = "1.3.1"
  , level         = "A"
  , title         = "A document must contain at most one `<main>` landmark"
  , confidence    = Structural
  , severity      = Error
  , source        = Cribrum
  , actId         = ""
  , ruleType      = ""
  , wcagAll       = []
  , applicability = ""
  , expectation   = ""
  }

--------------------------------------------------------------------------------
-- All rules in the catalog, lexicographically sorted by id.
--------------------------------------------------------------------------------

public export
generatedRules : List Rule
generatedRules =
  [ ruleActAriaStateOrPropertyHasValidValue6a7281
  , ruleActAttributeIsNotDuplicatedE6952f
  , ruleActAutocompleteAttributeHasValidValue73f2c2
  , ruleActButtonHasNonEmptyAccessibleName97a4e1
  , ruleActFormFieldHasNonEmptyAccessibleNameE086e5
  , ruleActHtmlPageHasLangAttributeB5c3f8
  , ruleActHtmlPageHasNonEmptyTitle2779a5
  , ruleActIdAttributeValueIsUnique3ea0c8
  , ruleActIframeElementHasNonEmptyAccessibleNameCae760
  , ruleActImageButtonHasNonEmptyAccessibleName59796f
  , ruleActImageHasNonEmptyAccessibleName23a2a8
  , ruleActLinkHasNonEmptyAccessibleNameC487ae
  , ruleActMetaViewportAllowsForZoomB4f0c3
  , ruleActObjectElementRenderingNonTextContentHasNonEmptyAccessibleName8fc3b6
  , ruleActRoleAttributeHasValidValue674b10
  , ruleActSummaryElementHasNonEmptyAccessibleName2t702h
  , ruleAltMeaningful
  , ruleAnchorHref
  , ruleAreaAlt
  , ruleAriaHiddenBody
  , ruleAriaLabelRedundant
  , ruleAriaRoleValid
  , ruleAudioDescription
  , ruleAutocompleteValid
  , ruleButtonName
  , ruleCaptionFirstChild
  , ruleCaptionsLive
  , ruleCharacterKeyShortcuts
  , ruleConsistentIdentification
  , ruleConsistentNavigation
  , ruleContentOnHoverFocus
  , ruleContrastMinimum
  , ruleDocumentLang
  , ruleDuplicateId
  , ruleErrorIdentification
  , ruleErrorPreventionLegal
  , ruleErrorSuggestion
  , ruleFieldsetLegend
  , ruleFocusVisible
  , ruleHeadingNoSkip
  , ruleIframeTitle
  , ruleImagesOfText
  , ruleImgAlt
  , ruleInputButtonName
  , ruleInputImageAlt
  , ruleKeyboard
  , ruleLabelFor
  , ruleLabelInName
  , ruleLinkEmptyHref
  , ruleLinkName
  , ruleMetaNoRefresh
  , ruleMotionActuation
  , ruleNoEmptyHeading
  , ruleNoKeyboardTrap
  , ruleNonTextContrast
  , ruleObjectName
  , ruleOrientation
  , rulePointerCancellation
  , rulePointerGestures
  , rulePositiveTabindex
  , ruleReflow
  , ruleResizeText
  , ruleSelectHasOptions
  , ruleStatusMessages
  , ruleSummaryNotEmpty
  , ruleTextSpacing
  , ruleThHasName
  , ruleThScopeValid
  , ruleTrackKind
  , ruleUniqueMain
  ]
