||| AUTO-GENERATED by ingest/aa-catalog.ts — do not edit by hand.
||| aa.ts: sha256 d2f3c0bc288ae21ee982e5476e41e6d210cad76fb317627556f4192be1747df6
||| catalog hash: sha256 43f720ba24183f91b43fa6afdce28660cfddf0d92eb07190c522dd59226a2ff7
module Cribrum.AA.Catalog.Generated

import Cribrum.AA.Catalog.Types

%default total

--------------------------------------------------------------------------------
-- Per-rule constants.
--------------------------------------------------------------------------------

public export
ruleAltMeaningful : Rule
ruleAltMeaningful = MkRule
  { id         = "alt-meaningful"
  , wcag       = "1.1.1"
  , level      = "A"
  , title      = "`alt` text must be meaningful (not just filename or empty)"
  , confidence = Heuristic
  , severity   = Warning
  }

public export
ruleAnchorHref : Rule
ruleAnchorHref = MkRule
  { id         = "anchor-href"
  , wcag       = "2.4.4"
  , level      = "A"
  , title      = "Anchor (`<a>`) must have an `href` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleButtonName : Rule
ruleButtonName = MkRule
  { id         = "button-name"
  , wcag       = "4.1.2"
  , level      = "A"
  , title      = "Each `<button>` must have an accessible name (text content or `aria-label`)"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleDocumentLang : Rule
ruleDocumentLang = MkRule
  { id         = "document-lang"
  , wcag       = "3.1.1"
  , level      = "A"
  , title      = "The `<html>` root must carry a non-empty `lang` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleDuplicateId : Rule
ruleDuplicateId = MkRule
  { id         = "duplicate-id"
  , wcag       = "4.1.1"
  , level      = "A"
  , title      = "No two elements may share the same `id`"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleFieldsetLegend : Rule
ruleFieldsetLegend = MkRule
  { id         = "fieldset-legend"
  , wcag       = "1.3.1"
  , level      = "A"
  , title      = "Each `<fieldset>` should contain a `<legend>` as its accessible name"
  , confidence = Structural
  , severity   = Warning
  }

public export
ruleHeadingNoSkip : Rule
ruleHeadingNoSkip = MkRule
  { id         = "heading-no-skip"
  , wcag       = "1.3.1"
  , level      = "A"
  , title      = "Heading levels must not skip (e.g. h1 -> h3 disallowed)"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleIframeTitle : Rule
ruleIframeTitle = MkRule
  { id         = "iframe-title"
  , wcag       = "4.1.2"
  , level      = "A"
  , title      = "Each `<iframe>` must have a non-empty `title` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleImgAlt : Rule
ruleImgAlt = MkRule
  { id         = "img-alt"
  , wcag       = "1.1.1"
  , level      = "A"
  , title      = "Images must have an `alt` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleLabelFor : Rule
ruleLabelFor = MkRule
  { id         = "label-for-control"
  , wcag       = "1.3.1"
  , level      = "A"
  , title      = "Each `<label>` must have a `for` attribute or contain its control"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleLinkName : Rule
ruleLinkName = MkRule
  { id         = "link-name"
  , wcag       = "2.4.4"
  , level      = "A"
  , title      = "Each `<a>` with `href` must have accessible text (text content or `aria-label`)"
  , confidence = Structural
  , severity   = Error
  }

--------------------------------------------------------------------------------
-- All rules in the catalog, lexicographically sorted by id.
--------------------------------------------------------------------------------

public export
generatedRules : List Rule
generatedRules =
  [ ruleAltMeaningful
  , ruleAnchorHref
  , ruleButtonName
  , ruleDocumentLang
  , ruleDuplicateId
  , ruleFieldsetLegend
  , ruleHeadingNoSkip
  , ruleIframeTitle
  , ruleImgAlt
  , ruleLabelFor
  , ruleLinkName
  ]
