||| AUTO-GENERATED by ingest/aa-catalog.ts — do not edit by hand.
||| aa.ts: sha256 71edcd66a94c064ae87048809093486a5f609546177612092ff7b150d115d983
||| catalog hash: sha256 f3e137b3bf33eeb25ed5b892143b02082d784003781c8a8c3f589b3719342031
module Cribrum.AA.Catalog.Generated

import Cribrum.AA.Catalog.Types

%default total

--------------------------------------------------------------------------------
-- Per-rule constants.
--------------------------------------------------------------------------------

public export
ruleAltMeaningful : Rule
ruleAltMeaningful = MkRule
  { id         = "alt-meaningful"
  , wcag       = "1.1.1"
  , level      = "A"
  , title      = "`alt` text must be meaningful (not just filename or empty)"
  , confidence = Heuristic
  , severity   = Warning
  }

public export
ruleAnchorHref : Rule
ruleAnchorHref = MkRule
  { id         = "anchor-href"
  , wcag       = "2.4.4"
  , level      = "A"
  , title      = "Anchor (`<a>`) must have an `href` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleAreaAlt : Rule
ruleAreaAlt = MkRule
  { id         = "area-alt"
  , wcag       = "1.1.1"
  , level      = "A"
  , title      = "Each `<area>` with `href` must have an `alt` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleAriaLabelRedundant : Rule
ruleAriaLabelRedundant = MkRule
  { id         = "aria-label-redundant"
  , wcag       = "4.1.2"
  , level      = "AA"
  , title      = "`aria-label` should not duplicate the element's visible text"
  , confidence = Heuristic
  , severity   = Warning
  }

public export
ruleButtonName : Rule
ruleButtonName = MkRule
  { id         = "button-name"
  , wcag       = "4.1.2"
  , level      = "A"
  , title      = "Each `<button>` must have an accessible name (text content or `aria-label`)"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleDocumentLang : Rule
ruleDocumentLang = MkRule
  { id         = "document-lang"
  , wcag       = "3.1.1"
  , level      = "A"
  , title      = "The `<html>` root must carry a non-empty `lang` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleDuplicateId : Rule
ruleDuplicateId = MkRule
  { id         = "duplicate-id"
  , wcag       = "4.1.1"
  , level      = "A"
  , title      = "No two elements may share the same `id`"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleFieldsetLegend : Rule
ruleFieldsetLegend = MkRule
  { id         = "fieldset-legend"
  , wcag       = "1.3.1"
  , level      = "A"
  , title      = "Each `<fieldset>` should contain a `<legend>` as its accessible name"
  , confidence = Structural
  , severity   = Warning
  }

public export
ruleHeadingNoSkip : Rule
ruleHeadingNoSkip = MkRule
  { id         = "heading-no-skip"
  , wcag       = "1.3.1"
  , level      = "A"
  , title      = "Heading levels must not skip (e.g. h1 -> h3 disallowed)"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleIframeTitle : Rule
ruleIframeTitle = MkRule
  { id         = "iframe-title"
  , wcag       = "4.1.2"
  , level      = "A"
  , title      = "Each `<iframe>` must have a non-empty `title` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleImgAlt : Rule
ruleImgAlt = MkRule
  { id         = "img-alt"
  , wcag       = "1.1.1"
  , level      = "A"
  , title      = "Images must have an `alt` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleLabelFor : Rule
ruleLabelFor = MkRule
  { id         = "label-for-control"
  , wcag       = "1.3.1"
  , level      = "A"
  , title      = "Each `<label>` must have a `for` attribute or contain its control"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleLinkEmptyHref : Rule
ruleLinkEmptyHref = MkRule
  { id         = "link-empty-href"
  , wcag       = "2.4.4"
  , level      = "A"
  , title      = "`<a href=\"\">` is ineffective and rejected"
  , confidence = Structural
  , severity   = Warning
  }

public export
ruleLinkName : Rule
ruleLinkName = MkRule
  { id         = "link-name"
  , wcag       = "2.4.4"
  , level      = "A"
  , title      = "Each `<a>` with `href` must have accessible text (text content or `aria-label`)"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleMetaNoRefresh : Rule
ruleMetaNoRefresh = MkRule
  { id         = "meta-no-refresh"
  , wcag       = "2.2.1"
  , level      = "A"
  , title      = "`<meta http-equiv=\"refresh\">` triggers an unsolicited timeout"
  , confidence = Structural
  , severity   = Warning
  }

public export
rulePositiveTabindex : Rule
rulePositiveTabindex = MkRule
  { id         = "positive-tabindex"
  , wcag       = "2.4.3"
  , level      = "A"
  , title      = "Positive `tabindex` values disrupt natural focus order"
  , confidence = Heuristic
  , severity   = Warning
  }

public export
ruleSummaryNotEmpty : Rule
ruleSummaryNotEmpty = MkRule
  { id         = "summary-not-empty"
  , wcag       = "1.3.1"
  , level      = "A"
  , title      = "`<details>` must contain a non-empty `<summary>` for accessible name"
  , confidence = Structural
  , severity   = Warning
  }

public export
ruleTrackKind : Rule
ruleTrackKind = MkRule
  { id         = "track-kind"
  , wcag       = "1.2.2"
  , level      = "A"
  , title      = "Each `<track>` must declare a `kind` attribute"
  , confidence = Structural
  , severity   = Error
  }

public export
ruleUniqueMain : Rule
ruleUniqueMain = MkRule
  { id         = "unique-main"
  , wcag       = "1.3.1"
  , level      = "A"
  , title      = "A document must contain at most one `<main>` landmark"
  , confidence = Structural
  , severity   = Error
  }

--------------------------------------------------------------------------------
-- All rules in the catalog, lexicographically sorted by id.
--------------------------------------------------------------------------------

public export
generatedRules : List Rule
generatedRules =
  [ ruleAltMeaningful
  , ruleAnchorHref
  , ruleAreaAlt
  , ruleAriaLabelRedundant
  , ruleButtonName
  , ruleDocumentLang
  , ruleDuplicateId
  , ruleFieldsetLegend
  , ruleHeadingNoSkip
  , ruleIframeTitle
  , ruleImgAlt
  , ruleLabelFor
  , ruleLinkEmptyHref
  , ruleLinkName
  , ruleMetaNoRefresh
  , rulePositiveTabindex
  , ruleSummaryNotEmpty
  , ruleTrackKind
  , ruleUniqueMain
  ]
