||| AUTO-GENERATED by tools/render-docsnav — do not edit by hand.
|||
||| Source: README.dj headings (h2 -> TocItem level 1, h3 -> level 2).
||| Anchors are slugified from heading text by `Cribrum.Pipeline.Anchor`,
||| so they match the `id` attributes the same pipeline writes onto the
||| corresponding `<h2>`/`<h3>` elements in `index.html`.
module Generated

import TocData

%default total

public export
genTocItems : List TocItem
genTocItems =
  [ MkTocItem "What-Cribrum-is" "What Cribrum is" 1
  , MkTocItem "Current-status" "Current status" 1
  , MkTocItem "The-IR-single-tree-HExpr" "The IR (single-tree HExpr)" 2
  , MkTocItem "HTML-validity-as-a-refinement" "HTML validity as a refinement" 2
  , MkTocItem "AA-accessibility-as-a-refinement" "AA accessibility as a refinement" 2
  , MkTocItem "Phase-order" "Phase order" 1
  , MkTocItem "Phase-1-Djot-parser-elaborate" "Phase 1 — Djot parser + elaborate" 2
  , MkTocItem "Phase-2-Validity-in-types" "Phase 2 — Validity in types" 2
  , MkTocItem "Phase-3-AA-checking-pass" "Phase 3 — AA checking pass" 2
  , MkTocItem "Phase-4-Structural-AA-in-types" "Phase 4 — Structural AA in types" 2
  , MkTocItem "Phase-5-DOM-render" "Phase 5 — DOM render" 2
  , MkTocItem "TEAWeb-Elm-on-Cribrum" "TEAWeb — Elm++ on Cribrum" 1
  , MkTocItem "TEAWeb-runtime-dispatch" "TEAWeb runtime + dispatch" 2
  , MkTocItem "TEAWeb-typed-by-content-view-API" "TEAWeb typed-by-content view API" 2
  , MkTocItem "Convention-layer" "Convention layer" 1
  , MkTocItem "Ingest-pipeline" "Ingest pipeline" 1
  ]
